/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IzvestajIdRouteImport } from './routes/izvestaj.$id'
import { Route as IzvestajIdPrintRouteImport } from './routes/izvestaj.$id.print'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IzvestajIdRoute = IzvestajIdRouteImport.update({
  id: '/izvestaj/$id',
  path: '/izvestaj/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IzvestajIdPrintRoute = IzvestajIdPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => IzvestajIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/izvestaj/$id': typeof IzvestajIdRouteWithChildren
  '/izvestaj/$id/print': typeof IzvestajIdPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/izvestaj/$id': typeof IzvestajIdRouteWithChildren
  '/izvestaj/$id/print': typeof IzvestajIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/izvestaj/$id': typeof IzvestajIdRouteWithChildren
  '/izvestaj/$id/print': typeof IzvestajIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/izvestaj/$id'
    | '/izvestaj/$id/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/izvestaj/$id'
    | '/izvestaj/$id/print'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/reset-password'
    | '/izvestaj/$id'
    | '/izvestaj/$id/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  IzvestajIdRoute: typeof IzvestajIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/izvestaj/$id': {
      id: '/izvestaj/$id'
      path: '/izvestaj/$id'
      fullPath: '/izvestaj/$id'
      preLoaderRoute: typeof IzvestajIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/izvestaj/$id/print': {
      id: '/izvestaj/$id/print'
      path: '/print'
      fullPath: '/izvestaj/$id/print'
      preLoaderRoute: typeof IzvestajIdPrintRouteImport
      parentRoute: typeof IzvestajIdRoute
    }
  }
}

interface IzvestajIdRouteChildren {
  IzvestajIdPrintRoute: typeof IzvestajIdPrintRoute
}

const IzvestajIdRouteChildren: IzvestajIdRouteChildren = {
  IzvestajIdPrintRoute: IzvestajIdPrintRoute,
}

const IzvestajIdRouteWithChildren = IzvestajIdRoute._addFileChildren(
  IzvestajIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  IzvestajIdRoute: IzvestajIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
